### ISSUE TITLE
Error while running train_fg_cues.py

### ISSUE THREAD

**Issue by karthik-sem** [ascust/SEC-MXNet#14]
I have used your code to generate cues for a 2 category dataset.I got this runtime error while training the cues.Please do look into it
start training fg cues for SEC.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mxnet/symbol/symbol.py", line 1623, in simple_bind
    ctypes.byref(exe_handle)))
  File "/usr/local/lib/python3.5/dist-packages/mxnet/base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [08:47:13] src/storage/storage.cc:119: Compile with USE_CUDA=1 to enable GPU usage

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_fg_cues.py", line 56, in <module>
    momentum=conf.MOMENTUM, lr_decay=conf.LR_DECAY_FG, workspace=conf.WORKSPACE)
  File "/home/rashmi/SEC-MXNet-master/cores/train_multi_wrapper.py", line 40, in train_multi_wrapper
    label_shapes=data_iter.provide_label)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/module/module.py", line 429, in bind
    state_names=self._state_names)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/module/executor_group.py", line 279, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/module/executor_group.py", line 375, in bind_exec
    shared_group))
  File "/usr/local/lib/python3.5/dist-packages/mxnet/module/executor_group.py", line 662, in _bind_ith_exec
    shared_buffer=shared_data_arrays, **input_shapes)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/symbol/symbol.py", line 1629, in simple_bind
    raise RuntimeError(error_msg)
RuntimeError: simple_bind error. Arguments:
label: (15, 20)
data: (15, 3, 320, 320)
[08:33:20] src/storage/storage.cc:119: Compile with USE_CUDA=1 to enable GPU usage

**Comment by ascust** [comment]
Did you use mxnet with CUDA enabled?

**Comment by karthik-sem** [comment]
Yes @ascust we have to use mxnet with CUDA enabled.
pip install mxnet-cu100 
This will solve the issue.Thanks @ascust
